-- ユーザープロフィール拡張（オプション）
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP NULL,
ADD INDEX IF NOT EXISTS idx_is_active (is_active);